### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by kipusoep** [MindscapeHQ/raygun4net#117]
ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.HttpWebResponse'. 
Using version 2.0.0 of the Raygun4Net NuGet package.

[ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.HttpWebResponse'.]
    System.Net.HttpWebResponse.CheckDisposed():0
    System.Net.HttpWebResponse.get_StatusCode():6
    Mindscape.Raygun4Net.RaygunMessageBuilder.SetExceptionDetails(Exception exception) in e:\Users\Jason\Documents\GitHub\raygun4net\Mindscape.Raygun4Net\RaygunMessageBuilder.cs:84
    Mindscape.Raygun4Net.RaygunClient.BuildMessage(Exception exception, IList`1 tags, IDictionary userCustomData) in e:\Users\Jason\Documents\GitHub\raygun4net\Mindscape.Raygun4Net\RaygunClient.cs:179

Here's the logged error ID in Raygun, so you can look up the error inside the Raygun database ;-) 352682142

**Comment by kipusoep** [comment]
Still having this issue. Any updates? It's been reported more than a year ago.

**Comment by QuantumNightmare** [comment]
Thanks for pointing this out again. I will look into this for the next release which will be about a month from now.

**Comment by QuantumNightmare** [comment]
Raygun4Net v5.0.1 is now available which will catch any exceptions when attempting to get the response information. As I haven't been able to reproduce this issue, please let me know if it is not solved.
