### ISSUE TITLE
Option to ignore properties when serializing custom objects

### ISSUE THREAD

**Issue by QuantumNightmare** [MindscapeHQ/raygun4net#158]
Either have an option to provide a list of properties to ignore, or an attribute to place on properties, or a way to specify a separate JSON serializer to ignore sensitive properties from custom user objects.

Mentioned here: https://raygun.io/forums/thread/10069#10284

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
