### ISSUE TITLE
Exception reports do not include all exception information

### ISSUE THREAD

**Issue by roryprimrose** [MindscapeHQ/raygun4net#188]
We just got an error report on a System.Web.Http.HttpResponseException but the Raygun report does not contain any information about the exception to do anything about it. For example, the following is the exception detail reported.

```
"Error": {
          "Data": [],
          "ClassName": "System.Web.Http.HttpResponseException",
          "Message": "HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.",
          "StackTrace": [
               {
                    "LineNumber": 50,
                    "ClassName": "System.Web.Http.Controllers.ApiControllerActionSelector+ActionSelectorCacheItem",
                    "MethodName": "SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 27,
                    "ClassName": "System.Web.Http.Controllers.ApiControllerActionSelector",
                    "MethodName": "SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 28,
                    "ClassName": "Mindscape.Raygun4Net.WebApi.RaygunWebApiActionSelector",
                    "FileName": "e:\\Users\\Jason\\Documents\\GitHub\\raygun4net\\Mindscape.Raygun4Net45\\WebApi\\RaygunWebApiSelectors.cs",
                    "MethodName": "SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 82,
                    "ClassName": "System.Web.Http.ApiController",
                    "MethodName": "ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)"
               },
               {
                    "LineNumber": 291,
                    "ClassName": "System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1",
                    "MethodName": "MoveNext()"
               }
          ]
     }
```

Given the fields reported (Message, InnerError, Type and StackTrace), the exception is not JSON serialized. Instead it looks like just the Message, InnerException and StackTrace properties are picked out. This misses out a lot of detail from many exceptions that are raised. SqlException is another classic one where the detail is not in the message, but in custom child properties and collections.

Is it possible to serialize and report on the entire exception instance?

**Comment by skoub** [comment]
@jamiepenney, any news on that one?

**Comment by jamiepenney** [comment]
@skoub not really. It pretty much came down to "special case any exceptions that have really important info". We can't store the serialize the whole exception object - it's too much data and most of it is not useful. Any extra info should be passed in as Custom Data.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
