### ISSUE TITLE
Ignore certain properties from request body

### ISSUE THREAD

**Issue by girtsl** [MindscapeHQ/raygun4net#211]
With the implementation of #190 Raygun now captures the request body which might contain sensitive data.
Provide an option to ignore specific properties, similar as with form field names, cookies, etc. I imagine this will involve request body deserialization depending on the content type. Initially it would be sufficient to support the most popular content type(s) - JSON and maybe BSON.

This issue might overlap with #158.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
