### ISSUE TITLE
Missing the header content-type when sending json object to the server

### ISSUE THREAD

**Issue by skoub** [MindscapeHQ/raygun4net#218]
Is it by design that the header content-type is not set when sending the json object to the server? Since that you are sending a json object, it would be cleaner to add the content-type to the request.

I can add it if you want since that i need it anyway on my projects.

**Comment by QuantumNightmare** [comment]
Hi skoub,

Setting the header content-type is not required for the Raygun service, but if you need to add that in for your project, we'd be happy to merge in a PR.

**Comment by skoub** [comment]
i've sent a PR #219

**Comment by QuantumNightmare** [comment]
Thanks skoub, I've merged your PR now and will get back to you when this is available on NuGet

**Comment by skoub** [comment]
no problem!
