### ISSUE TITLE
Consider releasing Raygun4Net.Core or RaygunClient as a separate nuget package

### ISSUE THREAD

**Issue by girtsl** [MindscapeHQ/raygun4net#223]
First, some background.
We use [log4net.Raygun](https://bitbucket.org/plmw/log4net.raygun/overview) to integrate our existing manual error logging with Raygun. Before version 4 everything was in a single nuget package - Raygun4Net - and it was all you would need to send exceptions manually. Afaict, with version 4 the Web API and MVC stuff have been extracted into their own packages (which is great, btw) and common functionality placed in Raygun4Net.Core.
The issue with this, though, is that you can no longer use projects like log4net.Raygun (and others that reference Raygun4Net package) in WebAPI/MVC projects as they now have their own nuget packages.

I can think of multiple solutions that would resolve this issue:
1) log4net.Raygun to take dependency on Raygun4Net.Mvc rather than Raygun4Net. But if you only have a WebAPI project, this pulls back in the reference to System.Web which we all want to avoid.
2) log4net.Raygun to ditch any dependencies and fork Raygun4Net.Core, RaygunClient and any other code they deem necessary. I doubt the author or log4net.Raygun would go for something like this due to increased maintenance load.
3) extract the RaygunClient (w/o MVC-related features) into it's own project and offer that as a nuget package;
4) extract the RaygunClient (w/o MVC-related features) into Raygun4Net.Core and offer that as a nuget package.

Since an adapter project like log4net.Raygun does not need a dependency to either MVC or WebAPI, I would prefer either 3 or 4 as they both will enable developers to send exception info manually.

So, please consider implementing either option 3 or 4. I'm sure either of those options will aid the popularity of Raygun :)

P.S. I'm in no way related to the log4net.Raygun project, we simply use it.

Thanks,
Girts

**Comment by QuantumNightmare** [comment]
Hi Girts,

Thanks for posting this issue. We'll certainly be doing something to resolve these kinds of scenarios. The main idea is to try make the main Raygun4Net dll reference the core dll. That way the main Raygun4Net dll would mainly just contain the RaygunClient which closely matches your #3 suggestion. Unfortunately that still leave a clash between the RaygunClient in the main package and the MVC package, so to resolve this, we may need to make a breaking change to rename the MVC RaygunClient to RaygunMvcClient analogous to the naming we use in the WebApi provider.

We'll let you know how it goes when we try this out.

Regards
-Jason Fauchelle

**Comment by girtsl** [comment]
Hi,

It's great that you have already considered this! 
One benefit of #4 over #3 would be one dependency less if you already have referenced either of WebApi or Mvc packages. But that's for you to decide. 
In any case, both #3 and #4 would require the MVC client rename as you suggest.

Cheers,
Girts

**Comment by QuantumNightmare** [comment]
Hi Girts,

Raygun4Net version 5 has now been released. Here is the release post with more info: https://raygun.io/blog/2015/03/new-release-raygun4net-5-0/

As mentioned previously, the main dll now depends on the core dll. The main dll has also now been renamed to Raygun4Net4 to avoid conflicts with the core dll which is called Raygun4Net. Additionally the Raygun4Net.Mvc dll now depends on the main dll as a lot of the classes were common. No renaming needed to be done, so there are no API breaking changes.

All these changes mean that the Raygun4Net, Raygun4Net.Mvc and Raygun4Net.WebApi NuGet packages are compatible with each other.

Let me know if these helps you or not with using log4net.Raygun in your scenario.

I should also note that we couldn't implement your #4 suggestion as the RaygunClient class is different for use in the Mvc and WebApi packages. In particular, the Mvc RaygunClient uses System.Web, and so can't be in Core.

Regards
-Jason Fauchelle

**Comment by plmwong** [comment]
Hey @QuantumNightmare,

Thanks for the changes :)

Would it be at all possible to add the `void Send(RaygunMessage raygunMessage)` method as an abstract method to the `RaygunClientBase`, alongside the existing `void Send(Exception exception)`? All the `RaygunClient` implementations which inherit from `RaygunClientBase` appear to have this method on them (unless I've missed one while browsing the code), and it would make it easier to build libraries against the `RaygunClientBase` and then have them work across the different implementations.

Thanks again,
Phillip

**Comment by QuantumNightmare** [comment]
Hi @plmwong,

Yes, I've noted this down as something to look at adding in the next version. Each version is usually a month apart, so it will still be about a month before this is available.

In the mean time, feel free to make a branch with this change (if you haven't done so already) just so that you can check if there are any other changes we may need to make for you - wouldn't want to wait a month between every change.

Regards
-Jason Fauchelle

**Comment by QuantumNightmare** [comment]
Hi @plmwong,

Raygun4Net v5.0.1 which is now available includes the Send(RaygunMessage) method in the RaygunClientBase class. Let me know if you need anything else, or if you have any questions.

Regards
-Jason Fauchelle
