### ISSUE TITLE
Xamarin iOS Unified 4.2.0 - native linking fails for armv7s architecture

### ISSUE THREAD

**Issue by zfoltin** [MindscapeHQ/raygun4net#224]
To reproduce

Open the Raygun.iOS.Unified.Sample solution
Open project options
in iOS Application change Deployment Target to 6.0
in iOS Build / Advanced tab change Supported Architecture to ARMv7s

Ad-Hoc iPhone build fails with

Native linking error: file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/.../Components/raygun4net-4.2.0/samples/Raygun.iOS.Unified.Sample/Raygun.iOS.Unified.Sample/obj/iPhone/Ad-Hoc/mtouch-cache/libRaygun4iOS.a file '/Users/.../Components/raygun4net-4.2.0/samples/Raygun.iOS.Unified.Sample/Raygun.iOS.Unified.Sample/obj/iPhone/Ad-Hoc/mtouch-cache/libRaygun4iOS.a' for architecture armv7s

MTOUCHTASK: error MT5309: Native linking error: file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/.../Components/raygun4net-4.2.0/samples/Raygun.iOS.Unified.Sample/Raygun.iOS.Unified.Sample/obj/iPhone/Ad-Hoc/mtouch-cache/libRaygun4iOS.a file '/Users/.../Components/raygun4net-4.2.0/samples/Raygun.iOS.Unified.Sample/Raygun.iOS.Unified.Sample/obj/iPhone/Ad-Hoc/mtouch-cache/libRaygun4iOS.a' for architecture armv7s

Works fine with the 4.1.0 version of the component

(Using Xamarin Studio on Mac if relevant)

**Comment by QuantumNightmare** [comment]
Thanks for reporting this! We'll have a look into this soon.

**Comment by chriskoiak** [comment]
+1

**Comment by alpriest** [comment]
+1

**Comment by danyalaytekin** [comment]
@QuantumNightmare Any update please?  It's been two weeks.

**Comment by QuantumNightmare** [comment]
Apologies for lack of update. I've resolved this issue for the next Raygun4Net version which is awaiting a couple of other fixes and is expected to be released this week. I'll reply back once this is available.

**Comment by QuantumNightmare** [comment]
Hi all, Thanks for waiting. This issue is fixed in the latest version of Raygun4Net (v4.2.1). This is available right now from NuGet and the Xamarin Component Store.

**Comment by zfoltin** [comment]
Thanks @QuantumNightmare :+1:
