### ISSUE TITLE
ASP.NET MVC RaygunExceptionFilterAttribute not added when there is more than 1 global filter

### ISSUE THREAD

**Issue by georgehemmings** [MindscapeHQ/raygun4net#241]
https://github.com/MindscapeHQ/raygun4net/blob/29189242cf4d63c406d73e9f17ddd44c956f3fbc/Mindscape.Raygun4Net.Mvc/RaygunExceptionFilterAttacher.cs#L12

`RaygunExceptionFilterAttacher` only adds the `RaygunExceptionFilterAttribute` when there is only 1 global filter and that filter is `HandleErrorAttribute`.

I'm not sure why it needs to be so strict, is it not good enough to detect that the `HandleErrorAttribute` is one of the current global filters, regardless of any others.

In my app I have `HandleErrorAttribute` and `AuthorizeAttribute` as global filters. I'm having to add the `RaygunExceptionFilterAttribute` into the filters collection manually, which works fine, it's just made the setup a little confusing.

**Comment by jamiepenney** [comment]
I've wondered about this myself - I joined Raygun after it was added and no-one seems to know why it is this strict. There is a theory that it was to deal with a particular edge case in an earlier version of MVC, but I'm fairly certain the filter count conditional is counter-productive now. I'll pop a pull request in to remove it and we'll roll it out with the next version of the NuGet package.

**Comment by QuantumNightmare** [comment]
This change has been made in the latest release of Raygun4Net (v5.0.1). The RaygunExceptionFilterAttribute will now always be added as long as a HandleErrorAttribute is present. That will make things easier for you.
