### ISSUE TITLE
ASP.NET 5 / CoreCLR Support

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4net#251]
I've started working on this in a separate branch here: https://github.com/MindscapeHQ/raygun4net/tree/raygun4net.aspnet5

**Things that don't work / compile:**

- [x] SimpleJson - probably going to have to replace this with Json.Net
- [x] Stack traces - The StackTrace and StackFrame class aren't in CoreCLR beta3 so I can't test this in Visual Studio
- [x] Automatically setting the Name / Version on RaygunClientMessage - Can't use Type.Assembly
- [x] Background send of exceptions - need a replacement for ThreadPool.QueueWorkItem
- [x] Sending the exception message - need a replacement for WebClient (or the correct nuget package)
- [ ] SetMachineName - Environment.MachineName isn't available.
- [ ] EnvironmentMessageBuilder - none of the APIs we used for this class work anymore
- [x] FlagAsSend(Exception) - Can't check if exception.Data is a Dictionary<string, string> or inherits from this as the Reflection APIs have been paired back.

**Comment by CmdrKeen** [comment]
Just as a note, we did originally use JSON.NET, however we were plagued by issues with conflicts in peoples code (because they used it too, different versions, etc). It's also quite a lot bigger than we need.

We did originally try doing some stuff with ilMerge to write the JSON.NET assembly inside, but then issues still arose for those that compiled themselves and other weird stuff. 

Just sharing some history :-) *may* be better to fork simple JSON and dial it back to just what we need as a light weight .NET 5 supportive JSON handler.

**Comment by jamiepenney** [comment]
Chunks of the reflection APIs are missing at this point. The following methods and properties are missing that we need:

* Attribute.GetCustomAttribute
* Attribute.IsDefined
* Type.IsGenericType
* Type.IsValueType

Could replace `IsGenericType` with `GetGenericArguments().Length > 0` perhaps? Not sure how to replace IsValueType. The Attribute stuff is unfixable, but it looks like we might be able to remove it as we're not using the DataContract serialization bit code path.

**Comment by benaadams** [comment]
> Not sure how to replace IsValueType

`typeof(T).GetTypeInfo().IsValueType`

**Comment by jamiepenney** [comment]
Ok, just a recap of the work I've been doing on this branch:

* SimpleJson actually had a compile flag to use GetTypeInfo() to get the reflection Type info.
* StackTrace and the supporting classes have been added to the dnxcore50 framework
* Use GetTypeInfo() to get the Assembly for searching for the AssemblyTitleAttribute.
* ThreadPool.QueueWorkItem has been replaced with the Task Parallel Library
* Replaced WebClient with HttpClient
* Environment.MachineName still isn't supported (https://github.com/dotnet/corefx/issues/4306) not sure what we should do here yet.
* I've added a compilation directive around most of EnvironmentMessageBuilder so that it works in dnx451, but there isn't a way to get that information in a cross platform way yet so will have to leave that out for now.
* As above, the reflection APIs have made a comeback so I can do the same FlagAsSent checks as normal.

**Comment by jamiepenney** [comment]
There's a beta build of the provider here: https://www.nuget.org/packages/Mindscape.Raygun4Net.AspNetCore/0.1.0-beta1

I've also written a blog post about how to use it here: https://raygun.com/blog/2016/04/asp-net-core-support

Add any comments / bugs to the pull request here: https://github.com/MindscapeHQ/raygun4net/issues/292
