### ISSUE TITLE
Weird bug in .net 4 causes raygun to fail reading from config section

### ISSUE THREAD

**Issue by Vidarls** [MindscapeHQ/raygun4net#254]
This: https://support.microsoft.com/en-us/kb/2580188 is preventing me from reading custom config in my production environment as I am both on .net 4.0 and running of a network share.

The article suggests a workaround:

>To work around this issue, use the methods in the System.Configuration.Configuration class instead of in the System.Configuration.ConfigurationManager class.

Any chance you'll consider implementing the workaround? (There is quite the lead time for us on provisioning new environments in production, so I was hoping for a quicker fix from this end)

**Comment by jamiepenney** [comment]
I'm not seeing an easy way to get a Configuration object - according to the docs

> You can get a Configuration object by using the following classes:  
> The ConfigurationManager class, if your entity is a client application.
> The WebConfigurationManager class, if your entity is a Web application.

But wouldn't that also trigger the issue? Also there doesn't seem to be a method that gets a Configuration which represents the final merged Configuration (like what you would get by hitting AppSettings directly) unless I'm just being dense.

Any chance you could pop together a basic branch that shows how this would work?

**Comment by Vidarls** [comment]
I failed doing a simple reproduction outside Raygun. (When I tried, the bug was not triggered)

I am currently using log4net.Raygun and successfully setting my settings via that route, and as such I can not justify spending a lot of time shaving this particular yak at this time.

If you have managed to reproduce it and want ot have a go, I suspect this is the correct methods to use: (from https://msdn.microsoft.com/en-us/library/System.Configuration.Configuration(v=vs.100).aspx)

>The names of the methods that return a Configuration object begin with "Open".

If you are not prioritzing this right now, just close the issue, I'll re-open or create a new one if the bug becomes a problem again.
Thanks for responding, and sorry I can't be of any help right now.

**Comment by jamiepenney** [comment]
I haven't managed to reproduce it either - I wonder if it was stealth fixed in .NET 4.5? Close the issue for now and if someone else has it (or you experience it again) we'll take another look in the future.

**Comment by xt0rted** [comment]
[According to Microsoft](https://connect.microsoft.com/VisualStudio/feedback/details/634360/net-4-configurationmanager-getsection-throws-exception-running-from-network-share) this was fixed in 4.0 with the hotfix and in the initial release of 4.5

**Comment by Vidarls** [comment]
@xt0rted I know, but we have an unpatched .net 4.0 on our servers. (And it is a bit of a longwinded process to re-provision them) so I tried my luck here.

Anyway, I have a workaround for now using log4net.Raygun. Closing this for now.
