### ISSUE TITLE
No way to retrieve Raygun "ID" after .Send()?

### ISSUE THREAD

**Issue by nicholashead** [MindscapeHQ/raygun4net#258]
It seems weird that the `.Send()` method doesn't return anything. Surely it could return some sort of Raygun ID and/or URL, so that we can refer back/link to that issue? Maybe I'm missing something in the docs/code. Thanks!

**Comment by fundead** [comment]
Hi Nicholas,

Essentially, the system is asynchronous in multiple ways that conspire to make this unfeasible at the current stage. Both the `Send` and `SendInBackground` methods simply perform a POST to the Raygun API, at which point the payload is queued up and processing begins internally. The API only performs checks such as validating the Raygun plan's ability to accept new data for the current month. If it is accepted the payload enters a processing pipeline which may group it into an error or may even reject it outright (for instance if the appropriate flag is set on a permanently ignored group).

Thus, the payload is only assigned to an error group with a URL at some time in the future after it is received by the API. Depending on system load this can be up to a few seconds later, which would be an unacceptable delay to propagate to user's code making requests to the Raygun API by default. The benefit is the API calls return quickly (instantly if `SendInBackground` is used, or ~100ms if not depending on physical location) and user code can continue execution after its exception is delivered.

Sorry we can't be of any further assistance here!

Regards,

Callum Gavin
Mindscape Limited
