### ISSUE TITLE
OWIN support

### ISSUE THREAD

**Issue by kendaleiv** [MindscapeHQ/raygun4net#264]
Are there guidelines or recommendations for setting up Raygun as part of the OWIN pipeline (perhaps an OWIN middleware)? Or, is this something that may be implemented in the future?

Perhaps something similar to https://github.com/xt0rted/Raygun.Owin -- but, exists as part of this repository.

**Comment by jamiepenney** [comment]
Hi Ken,

I attempted to write a piece of Owin middleware - you can see the branch here: https://github.com/MindscapeHQ/raygun4net/tree/raygun4net.owin

I actually found it to be pretty useless. You really don't get much information about the error unless you are dealing with it inside the Application stack (so, handling it within ASP.NET MVC or whatever framework you are using). By the time the Owin middleware has gotten the exception, MVC has already handled it and won't give it to you, so you get an HTTP error code instead - this middleware https://github.com/MindscapeHQ/raygun4net/blob/596dd369ba0571bd53eec63469469b1da3c81665/Mindscape.Raygun4Net.Owin/Middleware/RaygunOwinExceptionMiddleware.cs only gets invoked if there was an exception in the Owin stack somewhere. Once the Application pipeline has started, you no longer get access to anything useful. You can see that Nancy does the same thing here: http://dhickey.ie/2014/02/bubbling-exceptions-in-nancy-up-the-owin-pipeline/

I honestly can't recommend using Raygun just as a piece of middleware, you are better off trying to integrate it with your Application framework. However feel free to try out my branch and see if there's anything you can add.

Cheers,
Jamie

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
