### ISSUE TITLE
Mindscape.Raygun4Net.Xamarin.iOS.Unified won't work when using ad hoc build with Link

### ISSUE THREAD

**Issue by nelsonsar** [MindscapeHQ/raygun4net#267]
We use Link to build our app for iOS. The thing is that in ```TaskScheduler_UnobservedTaskException``` Raygun tries to report an exception and fails with ```IndexOutOfRangeException``` caused by this piece od code:

```((AssemblyTitleAttribute)GetType().Assembly.GetCustomAttributes(typeof(AssemblyTitleAttribute), false)[0])``` in [RaygunClientMessage](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/Messages/RaygunClientMessage.cs).

Is there a way to avoid it? Thanks!

**Comment by QuantumNightmare** [comment]
Hi nelsonsar,

Thanks for pointing this out. We've released Raygun4Net 5.2 which includes a fix for this. Let us know if you have further questions about this.

-Jason Fauchelle
