### ISSUE TITLE
Could not install package 'Mindscape.Raygun4Net.WebApi 5.2.0'

### ISSUE THREAD

**Issue by acastr7** [MindscapeHQ/raygun4net#279]
Trying to install the WebApi nuget package into my MVC/Web Api .NET 4 project.

When I run the command Install-Package Mindscape.Raygun4Net.WebApi I get the following error:

Install-Package : Could not install package 'Mindscape.Raygun4Net.WebApi 5.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Does the Web Api Package only work with .Net 4.5?

**Comment by QuantumNightmare** [comment]
Yes, currently the Web Api package only supports .Net 4.5. I've added a note to look at .Net 4.0 support for the next version. There isn't currently a time frame of when the next version will be available, but I'll get back to you when it is.

**Comment by QuantumNightmare** [comment]
I've looked into this further now. Unfortunately Web API for .NET 4.0 (that is Web API lower than v5.1) does not have the ExceptionLogger class. This is used to detect unhandled exceptions, so with this missing, a Raygun provider targeting this version is not going to be very useful.

As your project is also MVC, I'd recommend you set up the Raygun4Net.MVC provider in your app which will be able to pick up the unhandled exceptions. Let me know if you have any problems or questions about this.

Documentation: https://raygun.io/docs/languages/net/mvc
