### ISSUE TITLE
UWP app crashes when using RayGun with .NET Native

### ISSUE THREAD

**Issue by MattWhilden** [MindscapeHQ/raygun4net#281]
Hello! I work on the .NET Native runtime and compiler team. Someone using your library recently uncovered a bug in the UWP runtime and I figured I'd add a pointer here in case someone else ran into similar difficulty. In particular, SimpleJson.SerializeValue can interact poorly with .NET Native for UWP. I have some other comments in the StackOverflow issue. 

http://stackoverflow.com/questions/34923594/why-does-raygun-on-net-native-cause-my-app-to-crash

I'm not sure that it warrants any attention from your side. We will have a fix heading out in VS Update 2 (roughly March/April). Let me know if you have any questions.

**Comment by QuantumNightmare** [comment]
Hi Matt,

Thanks for contacting us about this and pointing out where the issue affects SimpleJson, we really appreciate it.

-Jason Fauchelle

**Comment by MattWhilden** [comment]
No problem at all. If you have other questions or issues with .NET Native/UWP, please feel free to tag me. Happy to help.

**Comment by MattWhilden** [comment]
We have a fix for this issue that will be in the next update to these tools. If someone working on Raygun would like to try things out before we hit RTM, I'm happy to send out an invite to our Preview build. Just send a mail off to dotnetnative@microsoft.com to get hooked up!

**Comment by jesperll** [comment]
@MattWhilden So is it fixed in 23914.00 that was released yesterday?

**Comment by MattWhilden** [comment]
Yep. If you find this not to be the case please let me know.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
