### ISSUE TITLE
Can't seem to access RaygunRequestMessage Request or Response properties.

### ISSUE THREAD

**Issue by acastr7** [MindscapeHQ/raygun4net#289]
I am trying to access Request and Response properties on [RaygunMessageDetails](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/Messages/RaygunMessageDetails.cs) class but it doesn't appear to be in the Xamarin.iOS 5.3.0.0 nuget package. Are these properties not available on iOS?

**Comment by QuantumNightmare** [comment]
Hi acastr7,

These properties are not available in the Raygun4Net.Xamarin.iOS provider. They might be added in a future version though.

-Jason Fauchelle

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
