### ISSUE TITLE
Linking errors with Xamarin.iOS and Raygun v5.3.0

### ISSUE THREAD

**Issue by DavePilks** [MindscapeHQ/raygun4net#290]
I recently added v5.3.0 to my application and it will not compile. I get over 100 linking errors. I will include some listed below. I have tried adding a nuget package and the Xamarin Component, both ending in the same situation.

> Error MT5212: Native linking failed, duplicate symbol: '_plcrash__architecture__descriptor'. (MT5212) 
> Error MT5212: Native linking failed, duplicate symbol: '_plcrash__crash_report__binary_image__descriptor'. (MT5212)

**Comment by QuantumNightmare** [comment]
Hi Dave,

Thanks for contacting us. Do you also have Xamarin Insights installed in your app?

I have not been able to reproduce this issue. If you could send a full error list or/and a simple repro project to jfauchelle@raygun.io then that would be a huge help to solving this issue.

-Jason Fauchelle

**Comment by DavePilks** [comment]
Hi Jason,

I do also have Xamarin Insights installed? Is this what is causing the issue? Should I uninstall it? 

Ill drop you a mail with the error list so long.

Thanks for the speedy response.

**Comment by DavePilks** [comment]
Hi again,

I have confirmed that this was the issue. I removed Insights and it works perfectly now!

Thanks.

**Comment by QuantumNightmare** [comment]
Hi Dave,

Great to hear the issue is solved. If you ever want to install Xamarin Insights in your app along with Raygun, send through that error list and we'll fix the problem.

-Jason Fauchelle
