### ISSUE TITLE
IIS thread blocking issue because of slow WMI response

### ISSUE THREAD

**Issue by mehdyhaghy** [MindscapeHQ/raygun4net#291]
Microsoft DebugDiag Analysis Report for our IIS shows our threads are get blocked whenever a large number of exceptions are being raised (even though we send exceptions in background).
and it's caused by WMI calls.
please cache the results of methods that use WMI 
or provide a setting to disable them (at least for GetCpu method)

this is the .Net call stack in hang analysis:
`
DomainNeutralILStubClass.IL_STUB_PInvoke(System.String, System.String, Int32, System.Management.IWbemContext, System.Management.IEnumWbemClassObject ByRef, Int32, Int32, System.Management.IWbemServices, System.String, IntPtr, System.String)+280 
[[InlinedCallFrame]] 
System_Management_ni!System.Management.SecuredIWbemServicesHandler.ExecQuery_(System.String, System.String, Int32, System.Management.IWbemContext, System.Management.IEnumWbemClassObject ByRef)+c3 
System_Management_ni!System.Management.ManagementObjectSearcher.Get()+322 
Mindscape.Raygun4Net.Builders.RaygunEnvironmentMessageBuilder.GetCpu()+34 
Mindscape.Raygun4Net.Builders.RaygunEnvironmentMessageBuilder.Build()+293 
Mindscape.Raygun4Net.RaygunMessageBuilder.SetEnvironmentDetails()+10 
Mindscape.Raygun4Net.RaygunClient.BuildMessage(System.Exception, System.Collections.Generic.IList1, System.Collections.IDictionary, Mindscape.Raygun4Net.Messages.RaygunIdentifierMessage, System.Nullable1)+75 
Mindscape.Raygun4Net.RaygunClient.StripAndSend(System.Exception, System.Collections.Generic.IList1, System.Collections.IDictionary, Mindscape.Raygun4Net.Messages.RaygunIdentifierMessage, System.Nullable1)+91 
Mindscape.Raygun4Net.RaygunClient+<>c__DisplayClass5.b__2(System.Object)+8d 
mscorlib_ni!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)+42 
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+a7 
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+16 
mscorlib_ni!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()+60 
mscorlib_ni!System.Threading.ThreadPoolWorkQueue.Dispatch()+12f 
mscorlib_ni!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()+a 
[[DebuggerU2MCatchHandlerFrame]] 
[[ContextTransitionFrame]] 
[[DebuggerU2MCatchHandlerFrame]]`

**Comment by mehdyhaghy** [comment]
actually you have a fail-safe in code, a flag to get Cpu and OS information from Environment instead of WMI will fix this

**Comment by QuantumNightmare** [comment]
Thanks for the feedback. We can look into this for the next version of Raygun4Net

**Comment by mehdyhaghy** [comment]
Thank you,
I stress tested RaygunEnvironmentMessageBuilder.Build()
with threadLimit of 100 and Execution count of 10,000

   | dev	|  production
------------ | -------------  | -------------
min (ms)	 | 17 | 73
max (ms) | 209 | 2403
avg (ms) | 41 | 377

* dev machine is MacBook Pro Late 2013 - Windows 10
* production server is Dell R820 server with Opteron 6272 (64 cores) - Windows Server 2012 Standard

WMI queries for Dell PowerEdge are dead slow and this can easily fill up IIS thread queue and choke IIS.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
