### ISSUE TITLE
Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.

### ISSUE THREAD

**Issue by dharrisvelaro** [MindscapeHQ/raygun4net#293]
We're consistently getting this error. The entire stack seems to be from the Raygun code. How do we get rid of the error and / or is there an actual error behind this that we should be concerned with? We are using Raygun WebAPI ver. 5.3.0.0

{
     "MachineName": "RD0003FF700F76",
     "Version": "1.0.0.0",
     "Error": {
          "Data": {},
          "ClassName": "System.Web.Http.HttpResponseException",
          "Message": "Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.",
          "StackTrace": [
               {
                    "LineNumber": 50,
                    "ClassName": "System.Web.Http.Controllers.ApiControllerActionSelector+ActionSelectorCacheItem",
                    "MethodName": "SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 28,
                    "ClassName": "Mindscape.Raygun4Net.WebApi.RaygunWebApiActionSelector",
                    "FileName": "e:\\Users\\Jason\\Documents\\GitHub\\raygun4net\\Mindscape.Raygun4Net.WebApi\\RaygunWebApiSelectors.cs",
                    "MethodName": "SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 0,
                    "ClassName": "System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer+<>c__DisplayClass2",
                    "MethodName": "<System.Web.Http.Controllers.IHttpActionSelector.SelectAction>b__0()"
               },
               {
                    "LineNumber": 149,
                    "ClassName": "System.Web.Http.Tracing.ITraceWriterExtensions",
                    "MethodName": "TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace)"
               },
               {
                    "LineNumber": 102,
                    "ClassName": "System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer",
                    "MethodName": "System.Web.Http.Controllers.IHttpActionSelector.SelectAction(HttpControllerContext controllerContext)"
               },
               {
                    "LineNumber": 82,
                    "ClassName": "System.Web.Http.ApiController",
                    "MethodName": "ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)"
               },
               {
                    "LineNumber": 28,
                    "ClassName": "System.Web.Http.Tracing.Tracers.HttpControllerTracer+<ExecuteAsyncCore>d__5",
                    "MethodName": "MoveNext()"
               },
               {
                    "LineNumber": 26,
                    "ClassName": "System.Runtime.CompilerServices.TaskAwaiter",
                    "MethodName": "ThrowForNonSuccess(Task task)"
               },
               {
                    "LineNumber": 46,
                    "ClassName": "System.Runtime.CompilerServices.TaskAwaiter",
                    "MethodName": "HandleNonSuccessAndDebuggerNotification(Task task)"
               },
               {
                    "LineNumber": 474,
                    "ClassName": "System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__18`1",
                    "MethodName": "MoveNext()"
               },
               {
                    "LineNumber": 26,
                    "ClassName": "System.Runtime.CompilerServices.TaskAwaiter",
                    "MethodName": "ThrowForNonSuccess(Task task)"
               },
               {
                    "LineNumber": 46,
                    "ClassName": "System.Runtime.CompilerServices.TaskAwaiter",
                    "MethodName": "HandleNonSuccessAndDebuggerNotification(Task task)"
               },
               {
                    "LineNumber": 397,
                    "ClassName": "System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1",
                    "MethodName": "MoveNext()"
               }
          ]
     }
....
,
     "Response": {
          "StatusCode": 405,
          "StatusDescription": "Method Not Allowed"
     }

**Comment by QuantumNightmare** [comment]
Hi Derrick, Thanks for contacting us. Jeremy has replied to you about this, but as a recap - Raygun is mentioned in the stack trace due to the way these kind of exceptions are caught. Exceptions caused by selecting an api action don't get surfaced as an unhandled exception, so we capture them with a custom selector for you. The response section should show the error code to help determine the issue. Let us know if you have further questions. -Jason Fauchelle
