### ISSUE TITLE
SendInBackground with Exception.Data sends AlreadySentByRagun

### ISSUE THREAD

**Issue by nigel-sampson** [MindscapeHQ/raygun4net#294]
``` csharp
var exception = new Exception()
ex.Data["Custom Data"] = "Test";

var client = new RaygunClient();
client.SendInBackground(exception, null, exception.Data);
```

The above code causes a piece of custom data `AlreadySentByRagun` to appear in Raygun.

**Comment by QuantumNightmare** [comment]
Thanks Nigel,

The Raygun4Net provider uses this flag to prevent double-sending exception instances. We'll have a look at either stripping this out from being sent by the provider, or by not showing this flag in Raygun.

**Comment by nigel-sampson** [comment]
Yup, realise it's point, looking at the code just looks like it's being flagged as sent prematurely in `SendInBackground`

The thread is queued and then the exception is flagged but before it's actually sent.

Will raise a PR sometime this weekend.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
