### ISSUE TITLE
Events on RaygunClient before entering background thread

### ISSUE THREAD

**Issue by gregpakes** [MindscapeHQ/raygun4net#297]
Hi,

I have a requirement where I want to intercept an event on RaygunClient.  I have looked at CustomGroupingKey and SendingMessage events, but when used with the HttpModule, these fire on a background thread, after SendInBackground is called.

I have forked and have a working version with a new event called BeforeSendingMessage which makes sure the event is fired before calling the background thread.

Is this something that you would be interested in me creating a PR for?

If so, do I need to go and add all the functionality in all the RaygunClient.cs files for each project?

thanks,

Greg

**Comment by QuantumNightmare** [comment]
Hi Greg,

Apologies for the late reply. Feel free to create a PR, we can take a look at it when working on the next version. Don't worry about adding this support to all the .NET providers, we could do that.

-Jason Fauchelle

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
