### ISSUE TITLE
Xamarin.Mac Nuget Package?

### ISSUE THREAD

**Issue by bradleach** [MindscapeHQ/raygun4net#298]
Is there any particular reason that this library isn't targeting Xamarin.Mac (given it should be just a couple of extra lines in the nuspec file)?

Thanks for a great library and service!

**Comment by QuantumNightmare** [comment]
Hi, I've been meaning to add it into the NuGet package for a while now. I'll try get this done for the next version. If you happen to now the target strings for Mac classic and unified apis, that would be a huge help.

**Comment by bradleach** [comment]
Thanks! I believe the target string for Mac is "Xamarin.Mac20" (Source: https://developer.xamarin.com/guides/cross-platform/advanced/nuget/)

Here is an example: https://github.com/praeclarum/NGraphics/blob/master/NGraphics.nuspec

**Comment by QuantumNightmare** [comment]
Thanks for that.

**Comment by QuantumNightmare** [comment]
The latest Raygun4Net NuGet package (v 5.3.1) now includes the Unified Xamarin.Mac Raygun provider using target Xamarin.Mac20. The classic api doesn't seem to be supported in NuGet, so the classic Xamarin.Mac Raygun provider has not been included.

Hope that helps!

**Comment by fschwiet** [comment]
Should the readme.md be updated?  It still states a download is necessary: https://github.com/MindscapeHQ/raygun4net/blame/master/README.md#L337.  Our mac csproj has this:

 <PackageReference Include="Mindscape.Raygun4Net">

and in the build result I see

  Mindscape.Raygun4Net.Xamarin.Mac.Unified.dll

so I think we're alright given what I read in this issue.  But just looking at the readme.md I thought we might have a problem.

**Comment by QuantumNightmare** [comment]
Hi fschwiet,

Yes, thanks for pointing this out. I've removed that incorrect statement from the read me now. Xamarin.Mac is included in the NuGet package, no manual download of the dll is needed.
