### ISSUE TITLE
RaygunClient.SendStoredMessages should store enough details to resend for the same API key.

### ISSUE THREAD

**Issue by Eric-Cadwell** [MindscapeHQ/raygun4net#308]
If you have a library that is loaded in an application and both are using Raygun with different API keys it's possible that the SendStoredMessages will read failed messages from the isolated storage and send them on a client with the wrong API key.

The isolated storage or serialized message should have enough details to either only send again when the same API key is provided for the client or it should have enough details to send to raygun using the same api key it was originally sent with regardless of which client is used.

**Comment by QuantumNightmare** [comment]
Hi Eric,

Thanks for pointing this out. We'd overlooked the App + Library setup for isolated storage. We have ideas for improving this for a future version of Raygun4Net. Will respond here when it's fixed.

-Jason Fauchelle

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
