### ISSUE TITLE
StackTrace shows up as null in raygun website because Exception.TargetSite is null

### ISSUE THREAD

**Issue by sabz90** [MindscapeHQ/raygun4net#312]
So, I was trying to serialize exception objects and then deserialize it later down the line. When I deserialize Exception objects, the Exception.TargetSite property becomes null and it doesn't make very much sense for that to be serialized since it uses reflection etc.

I looked into the source code and in the method BuildStackTrace(Exception exception) present in file RaygunErrorMessageBuilder.cs, the stackTrace.GetFrames returns a null.

While there are some work arounds (eg., building a RaygunMessage from scratch), A fallback mechanism to use the Exception.Stacktrace property when the Exception.TargetSite property is null, would be great.
This is because, though the TargetSite property is null, the Exception.StackTrace is still present with the proper data.

**Comment by QuantumNightmare** [comment]
Thanks for reporting this issue. We'll have a look at fixing this for the next version of Raygun4Net.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
