### ISSUE TITLE
Make RaygunMessage Serializable

### ISSUE THREAD

**Issue by sabz90** [MindscapeHQ/raygun4net#315]
Sometimes I want to serialize the raygun message and store it locally in case there is no internet connection detected in the running system.

Please mark the RaygunMessage and the types that it consists off with the [Serializable] attribute.

**Comment by QuantumNightmare** [comment]
Hi sabz90,

Thanks for your suggestion. First I'd like to mention that Raygun4Net already has built-in offline support for most .NET platforms. If messages can't be sent, up to 10 of them get saved to be sent later. In a future version we will be adding an option to specify the number of stored messages, and might be increasing this low default too.

Let us know if you'll still need to implement the offline support yourself and we can have a look at adding the [Serializable] attributes in a future Raygun4Net version. Let me know which .NET platform you are working with and I can let you know if we provide built-in offline support for it.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
