### ISSUE TITLE
RaygunOfflineStorage folder in root of c:\

### ISSUE THREAD

**Issue by gregpakes** [MindscapeHQ/raygun4net#318]
Hi,

I am curious why all my servers have a folder called **RaygunOfflineStorage** in the root of the c:\?

I've looked at the source code and it seems to make a call to:

`IsolatedStorageFile.GetUserStoreForApplication(); `

to determine where to create the folder.

I can't see why it would return c:\.

Any ideas?

**Comment by QuantumNightmare** [comment]
Hi Greg,

I wouldn't expect Isolated Storage to somehow return C:, and I haven't found any information about it ever doing so. An older version of Raygun4Net used the local application data folder instead of isolated storage - this too should not be falling back to the C: drive.

Might someone have copied them there as a backup, or at some stage did someone write their own implementation of offline storage that put the folder there?

Do any of the folders contain contents?

-Jason Fauchelle

**Comment by gregpakes** [comment]
Hi Jason,

I'm afraid not - we have this deployed to 500+ servers and all exhibit the same folder in the root of c:\.

Thanks,

Greg

**Comment by QuantumNightmare** [comment]
The behavior of the latest version of Raygun4Net is to only create the folder in the event of failing to send a report to Raygun. Then, after all reports within the folder has been successfully sent, the folder is then deleted. While the folders exist, they should contain error reports in them. If you can get the name of such files, as well as the client name and client version that is logged within the file, that might help debug this issue.

If these folders do not contain any reports, then the folders may not have been created by Raygun4Net, or they have been copied there, or something may be preventing Raygun4Net from deleting them when empty.

What version of Raygun4Net is running in your app? Also, what type of Raygun4Net is involved? eg, client profile, raygun4net, or raygun4net .NET 4.0. You can find out by looking at error reports logged to your Raygun app and finding the client name and client version in the raw tab.

Does this app or any others that may be running on the servers use any other Raygun provider - be it official or third party?

Let me know if you have questions about any of this.

**Comment by gregpakes** [comment]
Apologies for the delay.  Here are answers:

- Virtually all servers (500+) contain this folder
- Generally the folder is empty
    - I am guessing this is because it is in the root of c:\, so the application is unable to delete the folder due to permissions.
- The web applications all run under ApplicationPoolIdentity, so how does it have permission to create a folder in the root of c:\ anyway?  Owner of the folder is the ApplicationPoolIdentity of the application pool.
- Raygun versions (we run a few versions):
    - Raygun4Net: 5.3.0
    - Raygun4js: 2.3.4
    - Custom Classic ASP provider (I can't see how this be responsible for the folder as it simply makes api calls).

**Comment by QuantumNightmare** [comment]
You mention that 'generally' the folder is empty, have you come across a folder with contents in it? If so, knowing the name of the files and the Client name and version stored in such files might help narrow down what is causing this.

Is there a RaygunOfflineStorage folder elsewhere on each server too?

I'm wondering if you delete some of these folders from the C drive, will they appear again? Might be tricky to test as the Raygun4Net client will only create it in the event of failing to send a report.

**Comment by gregpakes** [comment]
No I haven't found any folders with contents in.

No I haven't found other folders on the system.

I will try and delete the folder and let you know.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
