### ISSUE TITLE
Support task based send method (async)

### ISSUE THREAD

**Issue by willnogueira** [MindscapeHQ/raygun4net#319]
e.g. 
var ex = new Exception();
var apiKey = "";
var raygun = new RaygunClient(apiKey);
var task = raygun.SendAsync(ex);

----
under the hood that would mean using:

var task = client.UploadStringAsync (RaygunSettings.Settings.ApiEndpoint, message);

in https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net4/RaygunClient.cs

**Comment by willnogueira** [comment]
Another option, and probably more viable, is to have a single background worker (preferably implemented in an async-fashion). Similar to https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs
Ideas?

**Comment by phillip-haydon** [comment]
I think this is solved now, SendInBackground is Task based and Send is still synchronous. We also have a background worker to limit thread exhaustion or Azure SNAT Exceptions.
