### ISSUE TITLE
`HttpClient`s should not be new'd up on every send

### ISSUE THREAD

**Issue by FLGMwt** [MindscapeHQ/raygun4net#321]
It looks like all the `RaygunClient.Send`s new up an `HttpClient` for each request. According to [Microsoft](https://github.com/mspnp/performance-optimization/blob/master/ImproperInstantiation/docs/ImproperInstantiation.md), [this guy](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/), and our experience doing the same thing with `HttpClient`s at scale, this is a bad thing because of socket exhaustion.

Ideally, it would be nice to have a hook for the consuming application to provide a singleton `HttpClient` instance, but at the very least, the `HttpClient` should be a singleton within the raygun4net library.

Happy to jump in on this : )

**Comment by CmdrKeen** [comment]
Thanks for this, we'll incorporate it into our next update. Now that .NET Core has been updated along with the VS 2017 release, we'll issue an update soon. 

Appreciate your good spotting on this @FLGMwt !

**Comment by DanFTRX** [comment]
Has any progress been made on this?  This seems like a serious attack vector on any web server running Raygun as if you can induce raygun errors, it can starve the socket supply.

**Comment by DanFTRX** [comment]
Is this project still under active development?

**Comment by QuantumNightmare** [comment]
Yes, we still work on this project when we can. We record each issue as tickets in our back log along with tasks for all other parts of Raygun. These then get prioritized to specify the order that we work on them. We are not up to this task yet.

**Comment by grugcrood82** [comment]
Resolved by #409
