### ISSUE TITLE
Request for ASP.NET Core: allow HttpClient configuration

### ISSUE THREAD

**Issue by FLGMwt** [MindscapeHQ/raygun4net#322]
Before ASP.NET Core, we configured connection limits and SSL protocols using the static `ServicePointManager`:

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
ServicePointManager.DefaultConnectionLimit = 60;
```

`ServicePointManager` is no longer available and it looks like the [only way](http://stackoverflow.com/questions/39560249/servicepointmanager-in-asp-net-core) to configure this is at the instantiation of the `HttpClient`. 

I'm not *quite* sure what the configuration would look like, but given I hope #321 also gets in, it would have to be at initial setup.

**Comment by Obi-Dann** [comment]
cc @phillip-haydon there's a simple PR available fixing this issue #507
