### ISSUE TITLE
SocketException when checking disk space of unavailable network share

### ISSUE THREAD

**Issue by Ic3xX** [MindscapeHQ/raygun4net#323]
Recently i got an SocketException while sending exception details to raygun. After some digging i was able to track down the problem via the stacktrace to a network share which was not available anymore. Raygun was checking the disk space of this network share resulting in a SocketException. This behaviour seems strange to me, a network share should not influence my app from sending exceptions. Anyway after removing the network share manually everything works fine.

**Comment by CmdrKeen** [comment]
Hi @Ic3xX, thanks for reporting this. My hunch would be that it's driven off how we collect some system stats (even though we don't specifically look for network shares, maybe some of the API's we call do). Any chance, from your stack trace, you could point out where you think this is being driven from in the Raygun4Net provider? That way we could add a handler around it for SocketExceptions so they don't bubble up at the very least.

Thanks!

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
