### ISSUE TITLE
Missing references on the azure webjobs package

### ISSUE THREAD

**Issue by xt0rted** [MindscapeHQ/raygun4net#325]
The webjobs package references [Microsoft.Azure.WebJobs.Extensions](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions/) which isn't included in [Mindscape.Raygun4Net.Azure.WebJob.nuspec](https://github.com/MindscapeHQ/raygun4net/blob/113733d718c0bca50bedeedb7f4ff66d1e2ab4fb/Mindscape.Raygun4Net.Azure.WebJob.nuspec). NuGet will install the package but when you go to run your webjob it'll crash with a missing reference exception. Manually referencing the webjobs extensions package gets it working.

**Comment by xt0rted** [comment]
@UberMouse This is the only issue I've run into so far with the webjobs package.

**Comment by UberMouse** [comment]
Ah, I will have missed this because my test project already references it. Thanks for reporting it, I'll add the reference and push a new release.

**Comment by UberMouse** [comment]
New version up, let me know if this solves the problem. https://www.nuget.org/packages/Mindscape.Raygun4Net.Azure.WebJob/5.4.2

Also snuck in the change to tag all the unhandled exceptions with UnhandledException to be in line with the other providers.

**Comment by xt0rted** [comment]
Update looks good. Including that tag by default helped simplify my setup by quite a bit 👍 (not that there was much to start with).

**Comment by UberMouse** [comment]
Great, I'll merge the PR then. Thanks.
