### ISSUE TITLE
RaygunClient.SendInBackground() does not set Version to AssemblyVersion in ASP.NET

### ISSUE THREAD

**Issue by essizershinn** [MindscapeHQ/raygun4net#347]
It appears that `RaygunClient.SendInBackground()` cannot get the AssemblyVersion in ASP.NET because it calls [RaygunClient.BuildMessage()](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/RaygunClient.cs#L369) from a [ThreadPool queued work item](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/RaygunClient.cs#L308) so `HttpContext.Current` is null when `RaygunMessageBuilder.SetVersion(string)` looks at it.

Repro Steps
1. Create an instance of `RaygunClient` without an explicit ApplicationVersion (either in config or set in code).
2. Call `RaygunClient.SendInBackground(...)` from within an ASP.NET application.

Expected Behavior
- Version is set to AssemblyVersion

Actual Behavior
- Version is set to **Not Supplied**

Configuration
- Raygun4Net4 v5.2
- .NET 4.6.1 Full Framework / WebApi 2.2 or MVC 5
- Windows 10 Creators Update (1703) / IIS 10.0.15063.0

**Comment by QuantumNightmare** [comment]
Hi essizershinn

Thanks for reporting this issue. We'll take a look at resolving this for the next version of Raygun4Net.

**Comment by phillip-haydon** [comment]
This should no longer be an issue, if no app version is provided it will roll back to assembly version.
