### ISSUE TITLE
Adding additional data from the exception before it is sent

### ISSUE THREAD

**Issue by xt0rted** [MindscapeHQ/raygun4net#350]
Using the `SendingMessage` event handler I can hook-in and modify the message before it's sent, but is there a way to augment the message with additional information from the source exception?

I'm using [brandonseydel/MailChimp.Net ](https://github.com/brandonseydel/MailChimp.Net) and the [MailChimpException](https://github.com/brandonseydel/MailChimp.Net/blob/4155f19a061c0be47efaa40623a9f866a78ffe64/MailChimp.Net/Core/MailChimpException.cs) has custom properties which contain response information. I want this to be logged as part of the exception's data but short of getting the package author to update the exception is there any way to modify this with Raygun as it stands? I'm going to be sending a PR to try and include this info in the `Data` property but until then I need to find a way to include this.

The exceptions in question are being sent with the Azure WebJobs client so there's no way to customize the method that sends the exception without copying that project's source into mine.

**Comment by QuantumNightmare** [comment]
The SendingMessage event handler really should have provided the original Exception, but we overlooked that opportunity.

Fortunately, the CustomGroupingKey event makes up for it. This event also gets raised before the message is about to be serialized and sent, and also provides the RaygunMessage object that you can augment in almost any way you like such as attaching custom data. Additionally, you get the original Exception object which you'll be able to use to get the data that you're interested in and attach it to the RaygunMessage either as Data, Tags or UserCustomData.

I'll close this issue as the alternative event should be what you need to achieve the desired result. Feel free to re-open if it doesn't work out.

**Comment by xt0rted** [comment]
Thanks, I'll give this a try until MailChimp.Net can be updated.
