### ISSUE TITLE
ASP.NET Core: calls to Send can null out current HttpContext

### ISSUE THREAD

**Issue by gshackles** [MindscapeHQ/raygun4net#352]
It looks like there are some funny flows you can end up going down when using the ASP.NET Core version of `RaygunClient`. In the one I ran into, I was creating a new client by [passing in the context to the constructor](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs#L86). All of the `Send` overloads that _don't_ take a `HttpContext` parameter result in eventually passing a `null` value for `HttpContext` into `SendAsync`, which proceeds to [wipe out the previous value stored in the client](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs#L338).

Is this intentional, or should it do a `null` check before assigning that value? I'd be happy to throw up a PR for it too, but wanted to check if I was missing something first. 

In the `SendInBackground` flow it gets [read out first in `BuildRequestMessage`](https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs#L409) and added to the message before being nulled out.

**Comment by j5alive** [comment]
I don't believe this was intentional. If you'd like to add a PR to check for null then I can take a look and merge the change.

**Comment by gshackles** [comment]
@j5alive Here ya go! 😄  #353

**Comment by jscottnz** [comment]
@gshackles can you please take a look at the latest release of Raygun4Net ASP.NET Core . To my eye it look like this has been resolved.

https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs

https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs

**Comment by gshackles** [comment]
@jscottnz Whoops somehow missed this notification, sorry! I believe you're right, so will close things out for now and report back if it surfaces again. Thanks!
