### ISSUE TITLE
Message: The client is disconnected because the underlying request has been completed. There is no longer an HttpContext available.

### ISSUE THREAD

**Issue by DanFTRX** [MindscapeHQ/raygun4net#355]
Using IIS7 and raygun, I occasionally receive the following error report when uploading files:

Message: The client is disconnected because the underlying request has been completed. There is no longer an HttpContext available.

System.Web.HttpBufferlessInputStream.Read(Byte[] buffer, Int32 offset, Int32 count):151
System.Web.Http.WebHost.SeekableBufferedRequestStream.Seek(Int64 offset, SeekOrigin origin):158
System.Net.Http.DelegatingStream.Seek(Int64 offset, SeekOrigin origin):0
 
Mindscape.Raygun4Net.WebApi.RaygunWebApiDelegatingHandler+<SendAsync>d__0.MoveNext():431
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
System.Web.Http.HttpServer+<SendAsync>d__0.MoveNext():391

It appears the raygun is trying to read the request stream after the request has already finished?  Not really sure.

**Comment by QuantumNightmare** [comment]
Hi DanFTRX,
I've replied to your forum post here: https://raygun.com/forums/thread/92212#92236
