### ISSUE TITLE
README doesn't mention iOS native crash reporting

### ISSUE THREAD

**Issue by chaselal** [MindscapeHQ/raygun4net#356]
The README does not mention the `RaygunClient.Attach` overload that allows enabling iOS native crash reporting
https://github.com/MindscapeHQ/raygun4net/blob/62cd9ad3f0d4791e3908b0a749e8f20dbf5d1094/Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs#L296

Official blog post describing the feature https://raygun.com/blog/raygun-for-xamarin-ios-supports-unified-api-and-native-error-reporting/

This is a pretty important feature. I think it's worth including in the README.

**Comment by QuantumNightmare** [comment]
I agree, I've updated the readme now to mention how to enable native iOS crash reporting in the Xamarin.iOS provider.

**Comment by chaselal** [comment]
@QuantumNightmare FYI the Raygun site also doesn't mention it when you create a new app and pick Xamarin.iOS as the "language". It shows a snippet with the old Attach method in step 2, but the new overload is not shown.
