### ISSUE TITLE
NetStandard 2.0 support?

### ISSUE THREAD

**Issue by DamienDennehy** [MindscapeHQ/raygun4net#357]
As NetStandard 2.0 is [compatible](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) with .NET Framework 4.6.1, it looks like something that Raygun could support. It is on the product roadmap in the nearby future?

I know that Mindscape.Raygun4Net.AspNetCore supports NetStandard 1.4, but moving this support into the main Raygun NuGet would be a huge advantage. 

My team's goal is use the same Raygun NuGet package across our Android, Desktop and Web APIs.

**Comment by CmdrKeen** [comment]
Hi Damien,

Unfortunately our main .NET library for Raygun is designed to support back to .NET 2.0 so it's not likely we'll move that requirement to .NET 4.6.1 / NetStandard2 in the very near term. 

I'll chat more with the team but I suspect it might be smarter to simply evolved the Core provider to be more of a NetStandard provider, and keep it at feature parity.

**Comment by DamienDennehy** [comment]
Hi John,

Ah got it, understand the issue with .NET 2.0. Using the Core provider for NetStandard sounds great!

We would be happy to migrate from Mindscape.Raygun4Net.AspNetCore to Mindscape.Raygun4Net.Core as this would allow us to drop AspNetCore from our libraries.

**Comment by alastairs** [comment]
As far as I can see the Core library only defines the message types and doesn't provide much functionality. I'm currently looking at Raygun for .NET Core 2.0 command-line apps (back-end services) and would really appreciate a .NET Standard 2.0 implementation. 

How feasible would it be to, e.g. provide two NuGet packages, one that supports .NET Standard 2.0 (and thus .NET 4.6.1+), and one that supports the older .NET 2.0-3.5.2 frameworks?

**Comment by SergeBerwert** [comment]
Need .Net Standard 2.0 support too. We also us the Mindscape.Raygun4Net usually.

**Comment by j5alive** [comment]
The current Raygun4Net.AspNetCore library does work with Net Standard 2.0, however it does reference all the MVC libraries so is probably not something you want to use?
We'll be looking into this soon, but I can't say exactly when we'll have the libraries updated sorry.

**Comment by robertmiles3** [comment]
It's been 3 months...got an update?

**Comment by rogihee** [comment]
Please create a seperate NuGet with .Net Standard support, we need this as well

**Comment by anfomin** [comment]
Raygun4Net lacks .NET Core 2.0 support so I've created [custom library RaygunCore](https://github.com/anfomin/rayguncore) for every one.

**Comment by robertmiles3** [comment]
@CmdrKeen Any update? With respect, it seems odd to hamstring newer stuff with the idea of supporting all the way back to .NET 2.0 given that even 4.5.1 was EOL'd over 2 years ago.

**Comment by CmdrKeen** [comment]
@robertmiles3 I’ve had the team bump the priority around building out a NetStandard2 provider. Should be started this week.

**Comment by bartdkmediahuis** [comment]
Is this ticket still "open" because it's in preview state ? 
Or can this be used in production ?

**Comment by mduncan26** [comment]
@bartdkmediahuis Apologies it can be used in production. I will close this issue.

**Comment by DamienDennehy** [comment]
This is really excellent to hear. Thank you for the support!

**Comment by robertmiles3** [comment]
Thanks @CmdrKeen and @mduncan26!

**Comment by ZhengRaygun** [comment]
Hi everyone, we've now also published a blog post on our recent support for .NET Standard 2.0 and ASP.NET Core 2. You can read the details here: https://raygun.com/blog/net_core_2-0_support/

Thank you for your request!
