### ISSUE TITLE
RUM session not ended when user information changes

### ISSUE THREAD

**Issue by kentcb** [MindscapeHQ/raygun4net#359]
In scenarios where user information is changed via `UserInfo`, these changes are not picked up by future tracking calls. After discussions with Raygun support, it seems this is because the RUM session is not ended.

**Comment by DamienDennehy** [comment]
I also have this issue - is there a work-around?

**Comment by jscottnz** [comment]
Hi there. I'll have an engineer take a look and get back.

**Comment by UberMouse** [comment]
Hi @DamienDennehy, what platform are you using Raygun4Net on?

**Comment by DamienDennehy** [comment]
HI @UberMouse, we're using Xamarin Android.

I was able to repro the issue on a fresh app in VS...here's the scenario.

Activity1 - An anonymous activity. Raygun is configured here in OnCreate().

![image](https://user-images.githubusercontent.com/3924814/31800956-affcff46-b53c-11e7-8ccc-d41a416edd24.png)

The user in Raygun's Dashboard is anonymous and this is correct. 
On the click of a button, a user "Bob" is logged in. The Raygun User is updated & a second activity is started.

![image](https://user-images.githubusercontent.com/3924814/31801040-4e613d14-b53d-11e7-9a43-6897acd90513.png)

Activity2 - The activity starts. 
The user in Raygun's Dashboard is anonymous and this is wrong. 

![image](https://user-images.githubusercontent.com/3924814/31801055-65dfb9c0-b53d-11e7-8c92-c0ec4cb4abf6.png)

**Comment by UberMouse** [comment]
Hi Damien,

Thanks for that, certainly makes it a bit clearer. I'll investigate this next week when I get back into the office and keep you updated with my findings.

**Comment by DamienDennehy** [comment]
Just wondering if you had a chance to take a look at this? Thanks.

**Comment by mduncan26** [comment]
Hi Damien,

I will be taking over the investigation for Taylor. I am beginning to look into this issue now and will be in touch again once I've had a chance to reproduce the problem locally. Thank you for your patience. 

Regards,
Mitchell

**Comment by mduncan26** [comment]
Hi Damien,

I was able to reproduce the problem locally and resolve the issue. We will look to release a fix shortly. I will notify you when the fix is available. Thank you for your patience.

Regards,
Mitchell

**Comment by mduncan26** [comment]
Hi Damien,

Just another update to let you know we have delayed the release of the fix to the Xamarin Android provider to update the Xamarin iOS provider with the same fix. Both will be fixed and released next week. Thank you for your patience while we resolve these outstanding issues.

Regards,
Mitchell.

**Comment by DamienDennehy** [comment]
Sounds great! Thanks all 👍

**Comment by mduncan26** [comment]
Hi @DamienDennehy,

Unfortunately there has been delay with the release. We will be looking to do a release next week. I am sorry for the delay and I thank you for your patience.

Regards,
Mitchell.

**Comment by mduncan26** [comment]
Hi @DamienDennehy,

Sorry for the delay. The fixes to the RUM session not ending are available now with the Raygun4Net 5.5.3 release. Thank you for your patience.

Regards,
Mitchell.

**Comment by DamienDennehy** [comment]
Hi Mitchell,

Awesome, thank you and the team for fixing this :)

Cheers,
Damien
