### ISSUE TITLE
Breadcrumb support is missing from Raygun4Net.Xamarin.iOS and Raygun4Net.Xamarin.Android

### ISSUE THREAD

**Issue by CliffCawley** [MindscapeHQ/raygun4net#360]
Breadcrumb support is missing from Raygun4Net.Xamarin.iOS and Raygun4Net.Xamarin.Android but it's documented as available

**Comment by kentcb** [comment]
[Relevant](https://raygun.com/forums/thread/89929).

**Comment by mduncan26** [comment]
Closing issue as the Xamarin provider does not currently support breadcrumbs. We do plan on supporting breadcrumbs for these platforms in the future. That work is planned but not scheduled.
