### ISSUE TITLE
PopulateLocation only when should record level

### ISSUE THREAD

**Issue by snakefoot** [MindscapeHQ/raygun4net#370]
No need to call `PopulateLocation` when `ShouldRecord` returns `false`.

https://github.com/MindscapeHQ/raygun4net/blob/7acf911461b541a70d1d3b8d0d63d81021ccf272/Mindscape.Raygun4Net/Breadcrumbs/RaygunBreadcrumbs.cs#L36

https://github.com/MindscapeHQ/raygun4net/blob/7acf911461b541a70d1d3b8d0d63d81021ccf272/Mindscape.Raygun4Net/Breadcrumbs/RaygunBreadcrumbs.cs#L52

**Comment by phillip-haydon** [comment]
I believe this has been resolved, the check for `ShouldRecord` is on the entry to the function. Thanks.
