### ISSUE TITLE
Pass exception object through to RaygunClientBase.SendingMessage event

### ISSUE THREAD

**Issue by DanFTRX** [MindscapeHQ/raygun4net#390]
There are some cases in which information exists within the original exception object that is not serialized into the RaygunMessage object.  I would like to be able to view(and potentially extract into UserCustomData) such data during the "SendingMessage" event.

**Comment by QuantumNightmare** [comment]
Thanks for this suggestion, I've Linked this into our internal issue tracker to be prioritized for a future release. I would also find this very useful to have.

**Comment by phillip-haydon** [comment]
This is now supported in .NET Core using IMessageBuilder, you can implement that interface and register it getting access to both the Message and the Exception. 

https://github.com/MindscapeHQ/raygun4net/blob/master/Raygun4Net.MSLogger.AspNetCore.Tests/Program.cs#L15
https://github.com/MindscapeHQ/raygun4net/blob/master/Raygun4Net.MSLogger.AspNetCore.Tests/Program.cs#L51-L59

Can see the registration and implementation example here. This is in v11.2.0 for:

Mindscape.Raygun4Net.AspNetCore
Mindscape.Raygun4Net.NetCore

And anything dependent on those packages, i.e Serilog, Extensions.Logging.
