### ISSUE TITLE
5.6 freezes xamarin.ios app on network changes

### ISSUE THREAD

**Issue by miszu** [MindscapeHQ/raygun4net#403]
The problem is the same as described in #372, after entering airplane mode/changing wifi network, the app freezes for some time (30-90 seconds), downgrading to 5.5.4 fixes it. Probably there's some work done on the main thread?

**Comment by mduncan26** [comment]
Hi Miszu,

Thank you for brining this to our attention. We will investigate into this issue and get back to you soon.

Regards,
Mitchell.

**Comment by mduncan26** [comment]
Hi Miszu,

We recently moved our Xamarin providers out of the main Raygun4Net NuGet package into their own standalone packages. Can you please try removing your current Raygun4Net provider and use the following.

https://www.nuget.org/packages/Mindscape.Raygun4Net.Xamarin.iOS.Unified/6.0.2

Regards,
Mitchell.

**Comment by mduncan26** [comment]
Closing this issue since the provider has been moved and updated to version 6.0.2.
