### ISSUE TITLE
High CPU and memory penalty when using certain types in userCustomData in RaygunClient.Send

### ISSUE THREAD

**Issue by ghost** [MindscapeHQ/raygun4net#404]
We had experienced one of our critical apps spiking CPU usage to 100%, allocating multiple GBs of memory and sometimes dying all together when trying to call RaygunClient.Send with userCustomData dictionary that has a value with one of the nested properties of type System.Exception.

Looking at the source code, it seems like .NET RaygunClient has a custom json-serialization (SimpleJson) that is not able to serialize Exception objects correctly. Depending on the exception's TargetSite the library allocates huge amount of memory and takes over the CPU.

I understand that using Exception properties in userCustomData is probably not advisable from error-reporting perspective. And it was not intentional on our side. However, I think this behavior should be considered erroneous because JSON serialization of Exception should not be done the way it is implemented in SimpleJson. For example, Newtonsoft.JSON does not have this problem because it relies on ISerializable implementation of Exception when serializing to json.

**Comment by phillip-haydon** [comment]
I believe this has been resolved, our implementation of SimpleJson no longer allows circular references.
