### ISSUE TITLE
Raygun does not install into a VS2019 Android 9 Xamarin.Android app.

### ISSUE THREAD

**Issue by DamienDennehy** [MindscapeHQ/raygun4net#406]
I'm following the instructions at https://raygun.com/documentation/language-guides/xamarin/crash-reporting/android/ and using the **Mindscape.Raygun4Net** package. 

Version: **Mindscape.Raygun4Net.5.7.0**

**To Repro:**
1. Create a new VS2019 Xamarin.Android project using Android 9.
![image](https://user-images.githubusercontent.com/3924814/57394110-8c1cd180-71bc-11e9-92be-7be3438ff999.png)

![image](https://user-images.githubusercontent.com/3924814/57394123-93dc7600-71bc-11e9-871b-e55169fa99ed.png)

2. Compile the solution - it will compile without any issues.

3. Install Raygun - it does not install.

**Error**
![image](https://user-images.githubusercontent.com/3924814/57394093-79a29800-71bc-11e9-852d-dd2891176521.png)

Package Mindscape.Raygun4Net 5.7.0 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1).

**Comment by xleon** [comment]
The package for Android is `Mindscape.Raygun4Net.Xamarin.Android`
