### ISSUE TITLE
Should there be a strong-named .NET Core package?

### ISSUE THREAD

**Issue by samblackburn** [MindscapeHQ/raygun4net#415]
Do you have reasons/principles behind not offering a signed .NET Core package, or would you be interested in reviewing a PR to add one?

This seems to be a question that's being raised in a few .NET projects, I'm not sure whether Raygun is in any way a special case.

#### Our use case
We have a lot of assemblies which are strong-named, and are starting to port our code to .NET Standard (for Linux support in some cases, but also to be ready for .NET 5 when it comes along).  I've noticed that for Raygun there are [strong-named .NET Framework packages](https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore/) but not strong-named .NET Core packages.

#### Workaround 1: We might be able to turn off strong naming in our code
We're currently investigating how difficult it would be to turn off strong naming.  Some justifications for strong naming are clearly dead (e.g. we used to use [LinkDemand](https://docs.microsoft.com/en-us/dotnet/framework/misc/link-demands)) and others have workarounds, for example `InternalsVisible` can be removed if we make a bunch of implementation details public (currently only visible to unit tests).

#### Workaround 2: We sign the package ourselves, but this adds complexity
Another option would be for us to sign the package ourselves and re-publish it to an internal feed - it looks like someone has done this [here](https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html).  I feel like this has unnecessary moving parts, though, which could break in a way that causes us to be unaware of new releases.

**Comment by QuantumNightmare** [comment]
Hi samblackburn,

We don't have a specific reason/principle behind not providing a signed .NET Core package other than not getting around to it yet, and not having much demand for it. So we are open to providing one, but will need to find some time to free up.

If we add this, we'd rather be the ones to create the PR, there's not much involved really - just adding the Sign configuration and updating the build script.

In the meantime, you could continue investigating workaround 1 and see how that goes. Workaround 2 does sound like a pain. If workaround 1 doesn't pan out, let us know and we'll see if we can get some time to add this in.

**Comment by mduncan26** [comment]
Hi @samblackburn 

We have just released a strong-named version of our .NET Core package.

It is available here on NuGet: https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore.Signed/

Please let us know if you encounter any issues.

Regards,
Mitchell.

**Comment by samblackburn** [comment]
Awesome, thanks!

Incidentally, I notice you've got some API differences between the .NET Core and .NET Framework versions - our library is dual targeted, so it ends up looking rather like this:
``` xml
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="Mindscape.Raygun4Net.Signed" Version="5.10.0" />
  </ItemGroup>
  <ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="Mindscape.Raygun4Net.NetCore.Signed" Version="6.2.0" />
  </ItemGroup>
```
``` c#
#if NETFRAMEWORK
            RaygunSettings.Settings.ApiEndpoint = endpointUrl;
            RaygunSettings.Settings.ThrowOnError = true;
            m_Client = new RaygunClient(apiKey);
#else
            m_Client = new RaygunClient(new RaygunSettings { ApiEndpoint = endpointUrl, ApiKey = apiKey, ThrowOnError = true });
#endif
```
This works absolutely fine, it just looks a little messy :)
