### ISSUE TITLE
Refactor NetCore package for singleton HttpClient as well.

### ISSUE THREAD

**Issue by DanFTRX** [MindscapeHQ/raygun4net#422]
It has already been done for the [AspNet package ](https://github.com/MindscapeHQ/raygun4net/pull/327)  But the .NetCore packages still instantiates a new HttpClient on every send, and it cannot be configured either.  Could the same/similar changes be made for the .Net Core Raygun?

https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs#L374

**Comment by BarsikV** [comment]
I don't really know what has been changed, but the AspNetCore package references the regular .NetCore.Common package. The RaygunClient class in AspNetCore uses the RaygunClientBase from the .Common package as a base class. Thus, it is creating a new HttpClient every time and exception is sent in all cases.

**Comment by DanFTRX** [comment]
@BarsikV You're right, my bad, its the Regular framework aspnet not the aspnet core that was updated.

**Comment by BarsikV** [comment]
This was first resolved by #409 , but then the PR was reverted by #410 . Please fix the issue with HttpClient and make it Singleton, static or configurable. It's harming our services.

**Comment by mduncan26** [comment]
Hi @BarsikV and @DanFTRX,

I apologise for this issue occurring again. We are working on some changes to the Raygun4Net providers right now and we will include a fix for this. I will update this thread once those changes are available.

Thank you,
Mitchell.

**Comment by BarsikV** [comment]
Thank you, me and my team very much appreciate it. Looking forward to it!

**Comment by mduncan26** [comment]
Hi @BarsikV and @DanFTRX,

We have just released an update (v6.3.1) to the .NET Core providers to use a single HTTP client.

https://www.nuget.org/packages/Mindscape.Raygun4Net.AspNetCore/6.3.1
https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore/6.3.1

Please update and let me know if the issue has been resolved.

Thank you for your patience.

Regards,
Mitchell.

**Comment by DanFTRX** [comment]
@mduncan26 WIth that back, maybe yall can revisit #322
