### ISSUE TITLE
Breadcrums not available on iOS / Android

### ISSUE THREAD

**Issue by xleon** [MindscapeHQ/raygun4net#427]
Currently we couldn't send breadcrums from the platform nugets, but only from the Xamarin.Forms implementation, which is far from ideal because XF is not yet initialised when the app is closed and a push notification arrives. 

Is there any way to send breadcrums from the platform nugets? 
Otherwise, are there any plans to support them?

**Comment by phillip-haydon** [comment]
As Xamarin is being discontinued we wont be adding support there, we in the process of adding breadcrumb support for usage in MAUI, which comes with Net Core / ASP.NET Core support.
