### ISSUE TITLE
Consider adding Raygun4Net's exception + userInfo SendInBackground overload to .NetCore package

### ISSUE THREAD

**Issue by josh-** [MindscapeHQ/raygun4net#428]
Hey there!

We're migrating from `Mindscape.Raygun4Net` to `Mindscape.Raygun4Net.NetCore`, however we've discovered that the overload to send an `exception` with `userInfo` is not available in the .NetCore package, as it is in the Raygun4Net package.

The source in the original package is here:

https://github.com/MindscapeHQ/raygun4net/blob/637422bc0c28a06f3dda26737f118a0c632a019a/Mindscape.Raygun4Net4.ClientProfile/RaygunClient.cs#L185

We use the same `RaygunClient` concurrently across multiple error reporting requests, and as such would prefer to use this overload instead of setting the `UserInfo` on `RaygunClient` before sending the request.

I'd be happy to open a PR with this functionality if it's something that you're open to considering. Cheers!

**Comment by mduncan26** [comment]
Hi @josh- ,

Yes we are open to PRs! The changes you raise make a lot of sense. I will make an internal ticket for this work, but please feel free to open a PR in the mean time for the changes you'd like to see.

Regards,
Mitchell.

**Comment by josh-** [comment]
Thanks so much @mduncan26! Will try and get a PR together shortly 👍
