### ISSUE TITLE
Lack of ConfigureAwait(false)

### ISSUE THREAD

**Issue by ceilingfish** [MindscapeHQ/raygun4net#451]
Hi,
It seems that the `Mindscape.Raygun4Net.NetCore.Common` nuget package does not call `ConfigureAwait(false)` on any of it's `await` calls. This causes issues when the code is called from a single threaded execution context (such as web forms or WPF). Is there a reason these have been omitted, and would you consider adding them?

**Comment by Havunen** [comment]
> such as web forms 

To my understanding .net core does not support webforms, not sure how it is in WPF (.net core)

**Comment by ceilingfish** [comment]
Indeed webforms does not support .net core, however this library is targeting netstandard, which can be referenced from net framework

**Comment by ceilingfish** [comment]
I've had a go at resolving this in #455

**Comment by krishnaKapadia** [comment]
@ceilingfish This is definitely something that we would be happy to take a look at. Are you able to provide a quick example or description of the problem that you are experiencing? It will help me to further understand your use case as well as test your changes.

Cheers

**Comment by JasenPalmer** [comment]
Solved in #455
