### ISSUE TITLE
HttpContext.Current is null when attaching RaygunWebApiClient 

### ISSUE THREAD

**Issue by andrei-tofan** [MindscapeHQ/raygun4net#452]
When we've added RaygunWebApiClient to a project using both  Web Forms and API programming models, we started to get exceptions that HttpContext.Current is null on file uploads. 

The setup looked something like this:
```c#
GlobalConfiguration.Configure(config =>
{
        RaygunWebApiClient.Attach(config);
       // ...
}
```

Any ideas why this may happen?

**Comment by abnercbalmeida** [comment]
My team and I are having the same problem in the same scenario :/

**Comment by phillip-haydon** [comment]
This should no longer be a problem, the client used to require the context to be set on a request by request basis but now thats encapsulated into the client itself.
