### ISSUE TITLE
Why Mindscape.Raygun4Net.AspNetCore needs Microsoft.AspNetCore.Http  (.NET5)

### ISSUE THREAD

**Issue by Havunen** [MindscapeHQ/raygun4net#453]
Hi

We are targetting .NET 5 in our project and it seems Raygun AspNetCore wants old assemblies as its dependency

      "Mindscape.Raygun4Net.AspNetCore/6.5.0": {
        "dependencies": {
          "Microsoft.AspNetCore.Http": "1.1.2",
          "Microsoft.AspNetCore.Http.Extensions": "1.1.2",
          "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.2",
          "Mindscape.Raygun4Net.NetCore.Common": "6.5.0"
        },

This causes warnings when building 
Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions" that could not be resolved.

Is it possible to add .NET5 version of nuget or use some abstraction please?

**Comment by Havunen** [comment]
Hi,

@Deacon-McIntyre can you review this please, I cannot seem to be able to assign reviews

**Comment by Deacon-McIntyre** [comment]
Hi @Havunen, thanks for the report and PR. We will take a look 👍

**Comment by Havunen** [comment]
Any news? Any chances getting those references excludes for .net5 they are causing issues for us

**Comment by JasenPalmer** [comment]
Fixed in PR #454 and released with PR #456
