### ISSUE TITLE
Cannot install latest version! Mindscape.Raygun4Net.AspNetCore": "6.6.3

### ISSUE THREAD

**Issue by Havunen** [MindscapeHQ/raygun4net#463]
NU1102: Unable to find package Mindscape.Raygun4Net.NetCore.Common with version (>= 6.5.2)
  - Found 10 version(s) in nuget.org [ Nearest version: 6.5.1 ]

NetCore.Common 6.5.2 or later version is missing from nuget https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore.Common/

ping @darcythomas

**Comment by darcythomas** [comment]
@Havunen Thanks for letting me know about this. 

I have pushed an update. Which should fix this.

Can you try again shortly (you may need to wait for it to be indexed by nuget first) and let me know if it is working for you now

**Comment by darcythomas** [comment]
Ok @Havunen I have tested on My Machine™

It seems to be working for me.
Can you please have another go, and let me know if it is working for you as well? :)

**Comment by Havunen** [comment]
I will check tomorrow

**Comment by darcythomas** [comment]
@Havunen Any luck today?

**Comment by Havunen** [comment]
Yeah 6.6.4 installed without any issues, closing this ticket :)
