### ISSUE TITLE
Breadcrumbs not available when upgrading a WinForms app to .NET (Core)

### ISSUE THREAD

**Issue by dougwaldron** [MindscapeHQ/raygun4net#465]
I utilize `RaygunClient.RecordBreadcrumb` in a .NET Framework WinForms app that I'm trying to upgrade to .NET 6. 

I've changed the NuGet package from "Mindscape.Raygun4Net" to "Mindscape.Raygun4Net.NetCore". Is this correct?

Now breadcrumbs are no longer available. Are there plans to implement this feature? Or is there an alternative?

FYI, your [documentation for using Breadcrumbs in .NET](https://raygun.com/documentation/language-guides/dotnet/crash-reporting/breadcrumbs/) does not mention that they aren't available in some types of apps.

**Comment by bounav** [comment]
Glad it's not just me!

I mentioned that to Raygun's customer support a few months ago, they confirmed that breadcrumbs are not supported in .net core after a bit of back and forth.

I suggested they make that _clearer_ in their documentation but they haven't got round to doing that it seems.

**Comment by phillip-haydon** [comment]
v10.0.0 is released with breadcrumb support.
