### ISSUE TITLE
Changelog or release history

### ISSUE THREAD

**Issue by Obi-Dann** [MindscapeHQ/raygun4net#484]
I fail to find changelog and release history for Mindscape.Raygun4Net.NetCore and Mindscape.Raygun4Net.AspNetCore 
The current nuget versions are 6.4.3 and 6.6.6 respectively, but there are no mentions of those versions in the release page. 
There's also no changelog and no tags in github, so there's pretty much no info on what's change and how it can affect our platform.

Does this info exist anywhere and I am just failing to find it?

**Comment by Hamish-taylor** [comment]
Currently there is no change log system for the releases of the individual raygun4net packages. However, we really appreciate you bringing this up to us and will be aiming to formalize this going forward. For the particular versions you mentioned I can tell you what was changed.
- Raygun4net.NetCore 6.4.3 was a minor version bump that had no code/functionality changes.
- Raygun4net.AspNetCore 6.6.6 was a minor update that fixed an issue that prevented developers from adding additional tags to exceptions if they were overriding the Raygun Client provider. If you are curious the code changes can be found in this [commit](https://github.com/MindscapeHQ/raygun4net/commit/cf1153c6e3c0517425bd2c5801f4de13d565bd12).

I hope this helps

**Comment by darcythomas** [comment]
There are some  times release notes put here: https://www.nuget.org/packages/Mindscape.Raygun4Net#readme-tab

However this has not been used consistently and we looking at improving this process.

**Comment by darcythomas** [comment]
@Obi-Dann 

We have moved to putting release notes in the [CHANGE-LOG.md](./CHANGE-LOG.md) file
We are moving to have unified the version numbers (7.0.0) across the various Raygun4net packages. 
We plan on releasing the Raygun4net packages in step going forward.


I hope that helps.
