### ISSUE TITLE
Changelog between 5.11.0 and 5.13.0, 6.0.3?

### ISSUE THREAD

**Issue by BlairMcClelland** [MindscapeHQ/raygun4net#485]
Hey team, 
The releases and tags stop at 5.11.0 however 5.x goes up to 5.13.0, are you please able to share the changelogs between these versions?
edit - also if it's possible to get the changes up to 6.0.3 for Raygun4Net, .Core, .WebApi, and .MVC?
Cheers

**Comment by darcythomas** [comment]
Hi Blair.

I will need to look in to the commit history for 5.11.0 - 5.13.0.

For the 6.0.0 - 6.0.3 that was me working out some wrinkles with the nuget build and deployment process, after the making the changes that bumped the version from 5.13.0 -> 6.0.0.


In hindsight I should have been using 6.0.0-beta-[001, 002, 003] in nuget land then I would have only need to a single 6.0.x release and change log.

Thanks for pointing this out. I will try and get this cleaned up for you shortly.

**Comment by BlairMcClelland** [comment]
Amazing thank you @darcythomas, I'm curious what were the major changes in 6.0.0?

**Comment by darcythomas** [comment]
Automatic Enabling of TLS 1.2 on environments which previously required
some manual configuration.

TLS 1.2 is a requirement of our endpoint.

This did mean dropping support for some versions of dotnet. Notably 2.0-3.5

Which is the reason for the major version bump, and cascading version bumps
for the our other dependent packages.

**Comment by darcythomas** [comment]
@BlairMcClelland I have dug the commit messages and created release notes for 5.12.0, 5.13.0, 5.14.0 (bonus!) and 6.0.0 - 6.0.3.

I am going to see if we can setup some processes to be something more standardised going forward.

Thanks for bring this to my attention :)
