### ISSUE TITLE
Memory Leak and Stability Concerns Introduced by UnhandledExceptionBridge Subscription in RaygunClientBase Constructor (#504)

### ISSUE THREAD

**Issue by Obi-Dann** [MindscapeHQ/raygun4net#508]
**Describe the bug**

Since version 8.1.0 `RaygunClientBase` subscribes to `UnhandledExceptionBridge.OnUnhandledException` in the constructor.
That means that RaygunClients will never be garbage collected, because their reference will be captured in `UnhandledExceptionBridge.OnUnhandledException` event handler.

In the context of AspNetCore, an instance of a raygun client is created for every request when an error occurs ([link to code](https://github.com/MindscapeHQ/raygun4net/blob/6d2678782c13561c118c8b0fe5277c1cf8e5239d/Mindscape.Raygun4Net.AspNetCore/RaygunClientProvider.cs#L21)).

At the very best, this change introduces a memory leak. At the worse it can have a significant impact on platform stability.

Link to the PR and line introducing the change https://github.com/MindscapeHQ/raygun4net/pull/504 ([this change](https://github.com/MindscapeHQ/raygun4net/pull/504/files#diff-e62b402362f36cf71400ff38c33a5280be1127c4eeac632fdb7e15d40cc2c370R102))

**Expected behavior**
What is the expected lifetime of `RaygunClientBase`?
If it's supposed to be a singleton, it shouldn't be created for every request in AspNetCore.
If it's supposed to be transient, it should be disposable to unsubscribe from the event handler.

**Comment by xenolightning** [comment]
You're absolutely right, and thanks for raising this.

We have been "treating" `RaygunClient` as a singleton more recently. But in reality this is not always the case.

In an ideal world RaygunClient should be a singleton, and we may make some adjustments to this (but this would likely be in a much later version)

We'll look to resolve this in two parts:
- The AspNetCore provider should be treating the client as a singleton
- We should be looking at `WeakReference` for the unhandled exceptions, so if a RaygunClient is transient, they can still be garbage collected

**Comment by Obi-Dann** [comment]
Well, if RaygunClient is considered singleton, then you might more concurrency issues. For example [here](https://github.com/MindscapeHQ/raygun4net/blob/072739d0bf10e525c50a89f088dfc248b5177ef3/Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs#L231-L235). 
I suspect multiple exceptions can be sent in parallel using the same client, but there's no locking on `_handlingRecursiveGrouping` and it can lead to non-deterministic behaviour?

**Comment by xenolightning** [comment]
> Well, if RaygunClient is considered singleton, then you might more concurrency issues. For example [here](https://github.com/MindscapeHQ/raygun4net/blob/072739d0bf10e525c50a89f088dfc248b5177ef3/Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs#L231-L235). I suspect multiple exceptions can be sent in parallel using the same client, but there's no locking on `_handlingRecursiveGrouping` and it can lead to non-deterministic behaviour?

Yeah, I use considered a singleton very loosely.

We have plans to change that approach, to do this the `RaygunClient` needs to be fully thread-safe. Which is a fairly large departure from the current implementation.

This is likely to be a major update, with no expected date as of yet

**Comment by xenolightning** [comment]
Fixed and released in 8.2.1, which can now be found on nuget:

https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore/8.2.1
