### ISSUE TITLE
Add default tags to outgoing errors

### ISSUE THREAD

**Issue by bmoscao** [MindscapeHQ/raygun4net#526]
**Is your feature request related to a problem? Please describe.**
With the deprecation of the following code, we can no longer hook centralized handlers on the `SendingMessage` event easily.
We used this approach to enrich all outgoing messages with tags that captured environment info, like service name, instance, etc.

```csharp
builder.Services.AddRaygun(builder.Configuration, new RaygunMiddlewareSettings
{
  // adds an optional example of over riding the client provider
  ClientProvider = new ExampleRaygunAspNetCoreClientProvider()
});
```

**Describe the solution you'd like**
Maybe an approach similar to `IRaygunUserProvider` or just extending RaygunSettings to allow for default tag list or configure event handlers directly on DI setup.

**Describe alternatives you've considered**
We considered getting the `RaygunClient` singleton from the DI container and adding the `SendingMessage` event handler, but it seems to be a bit of a hack.

**Comment by phillip-haydon** [comment]
Thanks for raising the issue, definitely an oversight, we will have to have a think about the best way to amend this.

In the short term you could do:

```
builder.Services.AddSingleton(s => 
{
  var client = new RaygunClient(s.GetService<RaygunSettings>()!, s.GetService<IRaygunUserProvider>()!);

  client.SendingMessage += (sender, eventArgs) =>
  {
    eventArgs.Message.Details.Tags.Add("Fruits!");
  };

  return client;
});

builder.Services.AddRaygun(builder.Configuration);
```

This should let you hook into the original functionality directly. Obviously this isn't an elegant solution, but it should unblock you while we decide on a cleaner solution.

**Comment by phillip-haydon** [comment]
https://raygun.com/forums/thread/186954

I was thinking of Tags being in settings but thinking about this forum post and this issue it might be worth while having a collection of 'plugins' or 'filters' which are invoked just before sending to allow for this custom type functionality.

**Comment by phillip-haydon** [comment]
DefaultTags can be easily added with a custom IMessageBuilder:

https://github.com/MindscapeHQ/raygun4net/blob/master/Raygun4Net.MSLogger.AspNetCore.Tests/Program.cs#L15
