### ISSUE TITLE
Upgrading from 9.x to 10.x, DefaultRaygunAspNetCoreClientProvider is lost

### ISSUE THREAD

**Issue by kim3er** [MindscapeHQ/raygun4net#527]
**Describe the bug**
When upgrading from 9.x to 10.x, `DefaultRaygunAspNetCoreClientProvider` is lost. The class is still referenced in documentation, and I am not able to find a migration guide.

**To Reproduce**
1. Update to 10.1.1 from 9.0.4.

**Expected behavior**
Either the class to still be there or have a migration guide.

**Comment by phillip-haydon** [comment]
Hello,

I'll get the docs amended.

https://github.com/MindscapeHQ/raygun4net/issues/526#issuecomment-2035531853

You can see an example here of how to use a custom client.

What were you using the client provider for? It would be helpful to understand your use case to see how we can accommodate for it.

**Comment by SamWilliamsGS** [comment]
Hi @phillip-haydon, we are having a similar problem with `IRaygunAspNetCoreClientProvider` being removed and we can no longer create custom client providers. Is there a new way of doing this or is it yet to be decided? I can't find anything in the docs, unfortunately they still reference the deleted interface (https://raygun.com/documentation/language-guides/dotnet/crash-reporting/aspnet/#manually-sending-exceptions-with-a-custom-clientprovider). Thanks 🙂

**Comment by phillip-haydon** [comment]
Hello @SamWilliamsGS sorry you ran into this, but it would be helpful to understand /why/ you need the client provider, what is the problem it solves for you?

**Comment by SamWilliamsGS** [comment]
Thanks @phillip-haydon! Our use cases generally revolve around modifying raygun messages in-flight to change the data by changing `RaygunClient.SendingMessage`. E.g. we may want to hard code an http status response, add the ID of the customer who triggered the crash, or add a new field at the middleware level that we use to correlate the message with other telemetry. Hope that makes sense, is there another way to do stuff like this now? 🙂

**Comment by kim3er** [comment]
My issue was resolved by following @phillip-haydon example in https://github.com/MindscapeHQ/raygun4net/issues/526#issuecomment-2035531853. Thanks for your help!
